"""Build the research record in one pass, from the store.

The record behind the research view was assembled by hand over many sessions,
and it drifted exactly the way hand-assembled things do: the equity section, the
IC section and the universe chart were still describing a 2021-10 window and an
older feature set while the headline analysis had moved to 2019-10, so the page
showed several mutually inconsistent studies without saying so. A reader has no
way to detect that, because every section looks equally authoritative.

This module exists so the record has one producer and one window. Everything it
emits is computed here, in this run, against the store as it is now. Sections
that cannot be computed are omitted rather than carried forward from a previous
build - a missing section is obvious, a stale one is not.

The long/short phase study is the one input taken from a file, because it costs
roughly an hour to compute; it carries its own window and is regenerated by
`scripts/phase_study.py`.
"""

from __future__ import annotations

import json
import math
from dataclasses import replace
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

import polars as pl

from . import backtest, features, ic as ic_mod, store, universe, validate
from .bars import mark_discontinuities
from .config import Config

#: The window every computed section uses. One window, stated once.
START = datetime(2019, 10, 1, tzinfo=timezone.utc)
END = datetime(2026, 8, 1, tzinfo=timezone.utc)

#: Signals to replay, and the label each gets on the page.
RUNS = (
    ("momentum", "xs_momentum", "conviction_tilt"),
    ("gc_breakout", "gc_breakout", "conviction_tilt"),
    ("baseline", "liquidity_top", "equal_weight"),
)

_HORIZONS = (7, 14, 30)


def _metrics(m) -> dict:
    return {
        "n": m.n,
        "total_return": float(m.total_return),
        "cagr": m.cagr,
        "volatility": m.volatility,
        "sharpe": m.sharpe,
        "max_drawdown": float(m.max_drawdown),
        # `turnover` and `cost_bps` are the names the report reads. Kept aligned
        # here rather than translated at render time, so the record is the
        # contract and a rename breaks the builder rather than the page.
        "turnover": float(m.turnover_per_rebalance),
        "cost_bps": float(m.cost_drag_bps),
        "rejected": m.rejected,
    }


def _data_block(bars: pl.DataFrame) -> dict:
    last = bars.group_by("asset").agg(pl.col("ts_utc").max().alias("last"))
    newest = bars["ts_utc"].max()
    dead = last.filter(pl.col("last") < newest - pl.duration(days=30)).height
    return {
        "assets": bars["asset"].n_unique(),
        "bars": bars.height,
        "delisted": dead,
        "first_bar": str(bars["ts_utc"].min().date()),
        "last_bar": str(newest.date()),
    }


def _universe_block(root: Path) -> list[dict]:
    """Eligible-vs-considered, sampled weekly across the record's own window."""
    out = []
    day = START
    while day <= END:
        try:
            members = universe.load(day, root=root)
        except FileNotFoundError:
            day += timedelta(days=7)
            continue
        out.append(
            {
                "date": day.date().isoformat(),
                "eligible": sum(1 for m in members if m.eligible),
                "considered": len(members),
                "dead": sum(1 for m in members if "delisted" in m.reason or "halted" in m.reason),
            }
        )
        day += timedelta(days=7)
    return out


def _runs_block(config: Config, root: Path, cash: Decimal) -> list[dict]:
    out = []
    for label, sig, ctor in RUNS:
        cfg = replace(config, signal=sig, constructor=ctor)
        result = backtest.replay(
            config=cfg, start=START, end=END, data_root=root, initial_cash=cash
        )
        stressed = backtest.replay(
            config=cfg, start=START, end=END, data_root=root, initial_cash=cash,
            slippage_multiple=Decimal(2),
        )
        wf = validate.walk_forward(result, interval_s=cfg.interval_s)
        out.append(
            {
                "label": label,
                "signal": sig,
                "constructor": ctor,
                "metrics": _metrics(backtest.metrics(result.steps, interval_s=cfg.interval_s)),
                "stressed": _metrics(
                    backtest.metrics(stressed.steps, interval_s=cfg.interval_s)
                ),
                # [date, value] pairs - the shape `nav_chart` unpacks.
                "nav": [[s.as_of.date().isoformat(), float(s.nav)] for s in result.steps],
                "folds": [
                    {
                        "start": f.test.dates[0].isoformat() if f.test.dates else "",
                        "end": f.test.dates[-1].isoformat() if f.test.dates else "",
                        "return": float(f.test.metrics.total_return),
                        "sharpe": f.test.metrics.sharpe,
                        "n": f.test.metrics.n,
                    }
                    for f in wf.folds
                ],
            }
        )
    return out


def _ic_block(config: Config, root: Path) -> list[dict]:
    results = ic_mod.measure(
        config=config, start=START, end=END, data_root=root, horizons_days=_HORIZONS
    )
    return [
        {
            "horizon": r.horizon_days,
            "periods": r.n_periods,
            "observations": r.n_observations,
            "effective_n": r.effective_n,
            "mean_ic": r.mean_ic,
            "std_ic": r.std_ic,
            "t_stat": r.t_stat,
            "hit_rate": r.hit_rate,
            "significant": abs(r.t_stat) >= 2.0,
            "disclosures": list(r.disclosures),
        }
        for r in results
    ]


def _spread_block(config: Config, root: Path, bars: pl.DataFrame) -> list[dict]:
    """Forward return of the above-channel group minus the below-channel group.

    The direct test of whether the channel separates anything, independent of
    how a portfolio built on it happens to perform. Kept separate from IC
    because it asks a coarser question - two groups rather than a full ranking -
    and a signal can pass one and fail the other.
    """
    frame = features.build(bars, benchmark=config.benchmark)
    prices = mark_discontinuities(bars).select(["asset", "ts_utc", "mark_open"])
    out = []
    for horizon in _HORIZONS:
        spreads, frac = [], []
        day = START
        while day <= END:
            try:
                members = universe.load(day, root=root)
            except FileNotFoundError:
                day += timedelta(days=7)
                continue
            elig = {m.asset for m in members if m.eligible}
            cx = frame.filter(
                (pl.col("ts_utc") == day - timedelta(seconds=config.interval_s))
                & pl.col("asset").is_in(list(elig))
                & (pl.col("bars_available") >= config.min_history_bars)
                & pl.col("adv_quote").is_not_null()
                & (pl.col("adv_quote") >= float(config.min_dollar_volume))
                & pl.col("vol_30").is_not_null()
                & (pl.col("vol_30") >= float(config.min_volatility))
                & pl.col("gc_upper").is_not_null()
            ).select(["asset", pl.col("gc_breakout_age").is_not_null().alias("above")])
            if cx.height >= 10:
                fwd = ic_mod._forward_returns(prices, cx["asset"].to_list(), day, horizon)
                j = cx.join(fwd, on="asset", how="inner").drop_nulls()
                a, b = j.filter(pl.col("above")), j.filter(~pl.col("above"))
                if a.height >= 3 and b.height >= 3:
                    spreads.append(
                        a["forward_return"].mean() - b["forward_return"].mean()
                    )
                    frac.append(a.height / j.height)
            day += timedelta(days=7)
        n = len(spreads)
        if n < 2:
            continue
        mean = sum(spreads) / n
        sd = math.sqrt(sum((s - mean) ** 2 for s in spreads) / (n - 1))
        # Overlap deflation, same reasoning as ICResult.effective_n: a 30-day
        # forward return sampled weekly reuses each window four times over.
        eff = n / max(1.0, horizon / 7)
        out.append({
            "horizon": horizon, "periods": n, "effective_n": eff,
            "mean_spread": mean,
            "t_stat": mean / (sd / math.sqrt(eff)) if sd else 0.0,
            "pct_above": sum(frac) / n,
        })
    return out


def build(*, config: Config, root: Path, cash: Decimal, phases: Path | None = None) -> dict:
    bars = store.read(root=root, interval_s=config.interval_s)

    record: dict = {
        "window": [START.date().isoformat(), END.date().isoformat()],
        "data": _data_block(bars),
        "universe": _universe_block(root),
        "runs": _runs_block(config, root, cash),
        "ic": _ic_block(config, root),
        "spread": _spread_block(config, root, bars),
    }
    if phases and phases.exists():
        record.update(json.loads(phases.read_text(encoding="utf-8")))
        _merge_candidates(record)
    return record


#: Where each replayed run belongs in the candidates table, and what it is for.
_RUN_ROWS = {
    "momentum": ("xs_momentum + conviction_tilt", "long-only", 1, "1 hypothesis",
                 "IC ~0 at every horizon; signal dead"),
    "gc_breakout": ("gc_breakout + conviction_tilt", "long-only", 1, "1 hypothesis",
                    "whipsaw; cadence sweep gave a width-1 peak"),
    "baseline": ("liquidity_top + equal_weight", "long-only", 0, "control",
                 "the null a ranking must beat"),
}


#: Where the two test windows meet. The phase study uses the same boundary.
SPLIT = "2021-10-01"


def _split_nav(nav: list, split: str) -> tuple[dict, dict]:
    """Return, Sharpe and drawdown either side of `split`, from a NAV series."""

    def stats(points: list) -> dict:
        if len(points) < 2:
            return {"return": 0.0, "sharpe": 0.0, "maxdd": 0.0}
        vals = [v for _, v in points]
        rets = [vals[i] / vals[i - 1] - 1 for i in range(1, len(vals))]
        mean = sum(rets) / len(rets)
        var = sum((r - mean) ** 2 for r in rets) / (len(rets) - 1) if len(rets) > 1 else 0.0
        sd = math.sqrt(var)
        peak, dd = vals[0], 0.0
        for v in vals:
            peak = max(peak, v)
            dd = min(dd, v / peak - 1)
        # 52 weekly periods a year; the record's runs rebalance weekly.
        return {
            "return": vals[-1] / vals[0] - 1,
            "sharpe": (mean * 52) / (sd * math.sqrt(52)) if sd else 0.0,
            "maxdd": dd,
        }

    return stats([p for p in nav if p[0] < split]), stats([p for p in nav if p[0] >= split])


def _merge_candidates(record: dict) -> None:
    """Put the replayed long-only rows in the same table as the phase rows.

    They come from different producers - `replay()` for these, the phase study
    for the rest - so the merge happens here rather than in either, and both are
    now measured over the same window. The long-only rows carry no phase spread
    because a strategy that lost 78-89% is not rescued by a different weekday;
    the column is left null rather than filled with a number that was not
    measured.
    """
    rows = []
    by_label = {r["label"]: r for r in record["runs"]}
    for label, (name, shape, cfgs, ev, note) in _RUN_ROWS.items():
        run = by_label.get(label)
        if run is None:
            continue
        # The table's columns are the two sub-windows, so these rows have to be
        # split the same way. Putting a full-window number under a column headed
        # "2021-10..2026-08" is the kind of quiet mislabelling that makes a table
        # of mixed provenance look like a like-for-like comparison.
        fresh, orig = _split_nav(run["nav"], SPLIT)
        rows.append({
            "name": name, "shape": shape, "configs": cfgs, "evidence": ev, "note": note,
            "fresh": fresh["return"], "fs": fresh["sharpe"], "fdd": fresh["maxdd"],
            "orig": orig["return"], "os": orig["sharpe"], "odd": orig["maxdd"],
            "combined": run["metrics"]["total_return"],
        })
    existing = record["combined"]["candidates"]
    # Benchmark first, then the long-only rows, then the long/short progression -
    # the order they were reached, which is the order the table claims to show.
    bench = [c for c in existing if c["shape"] == "benchmark"]
    rest = [c for c in existing if c["shape"] != "benchmark"]
    record["combined"]["candidates"] = bench + rows + rest
