[package]
name = "ib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ibapi = { version = "3", default-features = false, features = ["async"] }
venue = { workspace = true }
async-trait = { workspace = true }
rust_decimal = { workspace = true }
time = { workspace = true, features = ["formatting", "parsing", "macros"] }
tokio = { workspace = true, features = ["time", "sync"] }
