[package]
name = "runner"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
plan = { workspace = true }
venue = { workspace = true }
executor = { path = "../executor" }
records = { path = "../records" }
async-trait = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "time"] }
